name: mall
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluro: ^1.7.7
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.0.2
  shared_preferences: ^0.5.7+3
  dio: ^3.0.9
  flutter_spinkit: ^4.1.2
  provider: ^4.3.2
  cached_network_image: ^2.2.0+1
  fluttertoast: ^4.0.1
  pull_to_refresh: ^1.6.2
  flutter_widget_from_html_core: ^0.4.1
  tuple: ^1.0.3
  flutter_html: ^0.10.4
  city_pickers: ^0.1.30
  flutter_slidable: ^0.5.7
  flutter_webview_plugin: ^0.3.11
  common_utils: ^1.2.1
  event_bus: ^1.1.1
  device_preview: ^0.4.8
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/guide_1.png
    - images/guide_2.png
    - images/guide_3.png
    - images/404.png
    - images/default.png
    - images/network_error.png
    - images/no_data.png
    - images/arrow_right.png
    - images/coupon.png
    - images/close.png
    - images/bg_coupon.png
    - images/icon_to_be_evaluated.png
    - images/icon_to_be_delivered.png
    - images/icon_to_be_received.png
    - images/icon_to_be_paid.png
    - images/icon_location.png
    - images/icon_about_us.png
    - images/icon_feed_back.png
    - images/success.png
    - images/icon_order_status.png
    - images/icon_detail_location.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FMICon
      fonts:
        - asset: fonts/iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
